# Generated by Django 2.2.1 on 2019-07-18 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
